sudo: false
language: python
python: 
  - '2.7'
  - '3.4'
install: pip install -r requirements/test.txt
cache:
  directories:
  - $HOME/.cache/pip
script: coverage run --source=. manage.py test
after_success:
  coveralls
env:
- DJANGO_SETTINGS_MODULE=app.settings
notifications:
  slack:
    secure: OnxDxt6yk2kBiFRQ7UirobFntpqGA5qE6sQUfXgNPkksOlsMn7tyQw7VEBEiZ8zmEnhMxxqaUll/cVo33Faq+KEpFNXvJcyPf7D3l9JDjXvGxpmw2S3Tb4SIJBJc4iBPsVjS+ZJ7lU9xMki+XqcI8qFcolIhzPGwdP5q5RCrrkubalZLvNowxzho4O9Xt8RFJxtYJWr/uYqzRKGkg1w5kQKIe06//82U8q+1DH7/V1zM86QtUDXP8QLlhiYkEekzXXMvfrRYmR0W2uYNWX0Gu12oScZ8uGgmkDCSfQS505sRJD7hgIxyRXDbERAD5/EcuFoSXnRRYq7JKoZWPSuIlAXeKohCW/C/nM7TqqEZfgjLcFDcUWV63FBRY5LAqrQG+XI0Uh2ggpqQDptIOcEGon32x7L9XYzwyfzBCJZfgjyc94kuofAuTrzUGoOJPlwi5yDbxkIshe+LMgHJ9OvYarxFDMcDUB1S5IC+r3u2OMQ3R3y93XiereGKfeXftkrkI/R+375p4La8F/STUyxOFgSfGagVU1F8ce2fPaHAJYdx28p1t10+S/u02t2ABGzo3v/d/EyDl8++PZb23535BzXTwGjlpL4ZcAFObQNH89VzWvlZitKYdnwDf/icu5yWssTcWMFEEzo1OGGgfKVOzyk1vkNyucIm2IxJVaSFpwU=
