FORMAT: 1A
HOST: http://mymovie-api.maungawhau.net.nz/api/v1

# MyMovie

MyMovie is a web app for adding movies to a watchlist.
The server-side API provides endpoints for manipulating the items in a
watchlist - which is a list of associations between the user, a movie,
and what notifications they wish to receive.

Actions on users will be very minimal, and authentication will be via
social networks. Once authenticated with a social network the system will
retrieve and use name and avatar from the network.

The frontend UI is expected to search for movies directly on 3rd party services,
and use the movie ID when creating the watch list.

# Group Configuration

Resource with configuration data for the client,
such as
- notification types
- client id for social network auth

## Configuration [/config]

### Retrieve [GET]

+ Response 200 (application/json)


# Group Users and Authentication

Resources related to users of the system.

Login relies on authorising with a social network, and passing back
a token to use to get user details.

The system will return a JWT token, which must be passed back in an
Authorization header.


## Login with OAuth2 token [/auth/register-by-token/:social?access_token=:token]

After the front end preforms a login with a social service, it passes the token to the server
which registers the user in our system, exchanges the token for another token, and returns
our JWT token to the client.

+ Parameters
    + social: google-plus (string) - Name of the social service providing the authentication.
    + token: ya29.kQG0dHTiKO9 (string) - Access token from social service

### Login [GET]

+ Response 200 (application/json)

        {
            "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJvcmlnX2lhdCI6MTQzNDE1NzcwOSwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJqYW1lcyIsImVtYWlsIjoiamFtZXNAbWFpbGluYXRvci5jb20iLCJleHAiOjE0MzQxNzIxMDl9.WUv4q-HvrYRWmp60U3UtTgc11wNOaC4iSUnXYsda4YE",
            "user": {
                "last_name": "Mitchell",
                "avatar": "https://lh4.googleusercontent.com/-GorsEw8ovpc/AAAAAAAAAAI/AAAAAAAAAcw/wgKJc5pcZgo/photo.jpg?sz=50",
                "first_name": "James",
                "is_staff": true,
                "name": "James Mitchell",
                "last_login": "2015-06-13T01:08:29.151Z",
                "id": 1,
                "email": "james@mailinator.com"
            }
        }

## Login [/auth/login]

User login.

Depreciated in favour of social authentication.

### Login with email and password [POST]

+ Request (application/json)

        {
            "username": "test@example.com",
            "password": "password"
        }

+ Response 200 (application/json)

        {
            "id": 1,
            "email": "james@example.com",
            "name": "James Mitchell",
            "avatar": "http://www.example.com/avatar.jpg"
        }

## Users [/users/me]

User details.

### Retrieve [GET]

+ Request (application/json)
    
    + Headers
    
            Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJvcmlnX2lhdCI6MTQzNDE1NzcwOSwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJqYW1lcyIsImVtYWlsIjoiamFtZXNAbWFpbGluYXRvci5jb20iLCJleHAiOjE0MzQxNzIxMDl9.WUv4q-HvrYRWmp60U3UtTgc11wNOaC4iSUnXYsda4YE

+ Response 200 (application/json)

        {
            "id": 1,
            "email": "james@mailinator.com",
            "first_name": "James",
            "last_name": "Mitchell",
            "full_name": "James Mitchell",
            "avatar": "https://lh4.googleusercontent.com/-GorsEw8ovpc/AAAAAAAAAAI/AAAAAAAAAcw/wgKJc5pcZgo/photo.jpg?sz=50"
        }


# Group Movies and Watchlists

## Movie [/movies/{id}]

Resource for a movie.

**Note**: this is where a search endpoint would allow us to search and add
movies from the client - but we want search to use a 3rd party API, and to just
tell us what the movie details are.


+ Parameters
    + id: 1 (number) - Unique identifier for a movie
        
+ Model (application/json)

        {
            "id": 1,
            "name": "Star Trek",
            "poster": "http://ia.media-imdb.com/images/M/MV5BMjE5NDQ5OTE4Ml5BMl5BanBnXkFtZTcwOTE3NDIzMw@@._V1_SX300.jpg"
        }

### Retrieve [GET]

+ Response 200

    [Movie][]
        

## Watchlist [/watchlists/{id}]

Resource for watchlists.

+ Parameter
    + id: 1 (number) - Unique identifier for a watchlist

+ Model (application/json)

        {
            "id": 1,
            "movie":
                {
                    "id": 1,
                    "name": "Star Trek",
                    "poster": "http://ia.media-imdb.com/images/M/MV5BMjE5NDQ5OTE4Ml5BMl5BanBnXkFtZTcwOTE3NDIzMw@@._V1_SX300.jpg"
                },
            "notifications":
                [
                    {
                        "id": 1,
                        "type": "Cinema",
                        "notified": false,
                        "notified_date": ""
                    }
                ]
        }

### Retrieve [GET]

+ Request (application/json)

    + Headers

            Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJvcmlnX2lhdCI6MTQzNDE1NzcwOSwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJqYW1lcyIsImVtYWlsIjoiamFtZXNAbWFpbGluYXRvci5jb20iLCJleHAiOjE0MzQxNzIxMDl9.WUv4q-HvrYRWmp60U3UtTgc11wNOaC4iSUnXYsda4YE

+ Response 200

    [Watchlist][]

### Create [POST]


+ Request (application/json)

    + Headers

            Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJvcmlnX2lhdCI6MTQzNDE1NzcwOSwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJqYW1lcyIsImVtYWlsIjoiamFtZXNAbWFpbGluYXRvci5jb20iLCJleHAiOjE0MzQxNzIxMDl9.WUv4q-HvrYRWmp60U3UtTgc11wNOaC4iSUnXYsda4YE

    + Body
    
            {
                "movie": 
                    {
                        "name": "Star Trek",
                        "service": "omdb",
                        "service_id": "1"
                    },
                "notifications":
                    [
                        "Cinema", "Rental", "Streaming"
                    ]
            }

+ Response 201

    [Watchlist][]

### Update [PUT]

+ Request (application/json)

    + Headers

            Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJvcmlnX2lhdCI6MTQzNDE1NzcwOSwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJqYW1lcyIsImVtYWlsIjoiamFtZXNAbWFpbGluYXRvci5jb20iLCJleHAiOjE0MzQxNzIxMDl9.WUv4q-HvrYRWmp60U3UtTgc11wNOaC4iSUnXYsda4YE

+ Response 200

    [Watchlist][]


### Delete [DELETE]

+ Request (application/json)

    + Headers

            Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJvcmlnX2lhdCI6MTQzNDE1NzcwOSwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJqYW1lcyIsImVtYWlsIjoiamFtZXNAbWFpbGluYXRvci5jb20iLCJleHAiOjE0MzQxNzIxMDl9.WUv4q-HvrYRWmp60U3UtTgc11wNOaC4iSUnXYsda4YE


+ Response 204 (application/json)

## Watchlist Collection [/watchlists]

Resource for a list of user watchlists.

+ Model

        [
            {
                "id": 1,
                "movie":
                    {
                        "id": 1,
                        "name": "Star Trek",
                        "poster": "http://ia.media-imdb.com/images/M/MV5BMjE5NDQ5OTE4Ml5BMl5BanBnXkFtZTcwOTE3NDIzMw@@._V1_SX300.jpg"
                    },
                "notifications":
                    [
                        {
                            "id": 1,
                            "type": "Cinema",
                            "notified": false,
                            "notified_date": ""
                        }
                    ]
            }
        ]

### List [GET]

+ Request (application/json)

    + Headers

            Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJvcmlnX2lhdCI6MTQzNDE1NzcwOSwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJqYW1lcyIsImVtYWlsIjoiamFtZXNAbWFpbGluYXRvci5jb20iLCJleHAiOjE0MzQxNzIxMDl9.WUv4q-HvrYRWmp60U3UtTgc11wNOaC4iSUnXYsda4YE

+ Response 200
       [Watchlist Collection][]
        

## Notification [/watchlists/{list_id}/notifications/{id}]

+ Parameters
    + id: 1 (number) - Unique identifier for a notification
    + list_id: 1 (number) - Unique identifier for the watchlist

+ Model (application/json)

        {
            "id": 1,
            "type": "Cinema",
            "notified": false,
            "notified_date": ""
        }

### Create [POST]


+ Request (application/json)

    + Headers

            Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJvcmlnX2lhdCI6MTQzNDE1NzcwOSwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJqYW1lcyIsImVtYWlsIjoiamFtZXNAbWFpbGluYXRvci5jb20iLCJleHAiOjE0MzQxNzIxMDl9.WUv4q-HvrYRWmp60U3UtTgc11wNOaC4iSUnXYsda4YE

    + Body

            {
                "notification": "Cinema"
            }

+ Response 201

    [Notification][]

### Retrieve [GET]

+ Request (application/json)

    + Headers

            Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJvcmlnX2lhdCI6MTQzNDE1NzcwOSwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJqYW1lcyIsImVtYWlsIjoiamFtZXNAbWFpbGluYXRvci5jb20iLCJleHAiOjE0MzQxNzIxMDl9.WUv4q-HvrYRWmp60U3UtTgc11wNOaC4iSUnXYsda4YE

+ Response 200

    [Notification][]

### Update [PUT]

+ Request (application/json)

    + Headers

            Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJvcmlnX2lhdCI6MTQzNDE1NzcwOSwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJqYW1lcyIsImVtYWlsIjoiamFtZXNAbWFpbGluYXRvci5jb20iLCJleHAiOjE0MzQxNzIxMDl9.WUv4q-HvrYRWmp60U3UtTgc11wNOaC4iSUnXYsda4YE

+ Response 200

    [Notification][]

### Delete [DELETE]

+ Request (application/json)

    + Headers

            Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJvcmlnX2lhdCI6MTQzNDE1NzcwOSwidXNlcl9pZCI6MSwidXNlcm5hbWUiOiJqYW1lcyIsImVtYWlsIjoiamFtZXNAbWFpbGluYXRvci5jb20iLCJleHAiOjE0MzQxNzIxMDl9.WUv4q-HvrYRWmp60U3UtTgc11wNOaC4iSUnXYsda4YE

+ Response 204 (application/json)

## Notification Collection [/watchlists/{list_id}/notifications]

Resource for a list of notifications on a watchlist.

+ Parameters
    + list_id: 1 (number) - Unique identifier for the watchlist

+ Model (application/json)

        [
            {
                "id": 1,
                "type": "Cinema",
                "notified": false,
                "notified_date": ""
            }
        ]


