version: '3'
services:
  db:
    image: bitnami/mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD="movies"
      - MYSQL_USER="movies"
      - MYSQL_PASSWORD="movies"
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      default:
        aliases:
          - db.localhost

  cache:
    image: bitnami/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      default:
        aliases:
          - redis.localhost.

  # SMTP server to capture outgoing emails
  email:
    image: docker.io/mailhog/mailhog
    logging:
      driver: 'none'  # disable to verbose logs
    networks:
      default:
        aliases:
          - mailhog.localhost

  web:
    # Override the wsgi entrypoint. Run the development server listening on all interfaces
    # debugpy docs https://github.com/microsoft/debugpy
    entrypoint: ["sh", "-c", "pip install --no-cache -t /var/tmp/ debugpy && python /var/tmp/debugpy --listen 0.0.0.0:5678 /var/app/manage.py runserver 0.0.0.0:80"]
    ports:
      - "5678:5678" # debug port
    build: .
    restart: on-failure
    volumes:
      - .:/var/app
    read_only: true
    tmpfs:
      - /var/tmp:mode=770,uid=1000,gid=1000
    depends_on:
      - db
      - cache
    environment:
      SERVER_PORT: 80
      DJANGO_SETTINGS_MODULE: app.settings.production
      GOOGLE_PLUS_KEY: ${GOOGLE_PLUS_KEY:-''}
      GOOGLE_PLUS_SECRET: ${GOOGLE_PLUS_SECRET:-''}
      DATABASE_URL: "mysql://movies:movies@db:3306/movies"
    networks:
      default:
        aliases:
          - movies.localhost
