# Use this file to override the main docker-compose
# Enable the ports HERE if you wish to access the services on localhost outside docker
version: "3"

# Use this to link the default network to an external one you created
networks:
  default:
    name: shared_net
    external: true

services:
  # SMTP server for test emails
  # smtp port 1025
  # http port 8025 (exposed at 80)
  email:
    labels:
      # These labels enable traefik to route traffic to the container
      - "traefik.enable=true"
      - "traefik.http.routers.email.rule=Host(`mailhog.localhost`)"
      - "traefik.http.routers.email.entrypoints=web"
      - "traefik.http.services.email.loadbalancer.server.port=8025"
    entrypoint: ["/bin/sh", "-c", "MailHog &>/dev/null"]

  web:
    # Use these labels along with Traefik above to enable "load balancing"
    # and being able to scale up the running containers
    labels:
      # These labels enable traefik to route traffic to the container
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`movies.localhost`)"
      - "traefik.http.routers.app.entrypoints=web"
      - "traefik.http.services.app.loadbalancer.server.port=8000"
    environment:
      DJANGO_SETTINGS_MODULE: app.settings.development
