# Generated by Django 4.1 on 2022-09-04 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("poster", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "year",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        null=True,
                        verbose_name="Year of Release",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Watchlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="movie",
            name="subscribers",
            field=models.ManyToManyField(
                through="movies.Watchlist", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="ServiceMovie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_id", models.CharField(db_index=True, max_length=50)),
                (
                    "service",
                    models.CharField(
                        choices=[("omdb", "Open Movie Database")],
                        db_index=True,
                        default="omdb",
                        max_length=10,
                    ),
                ),
                ("service_data", jsonfield.fields.JSONField(blank=True, null=True)),
                ("updated", models.DateField(blank=True, db_index=True, null=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
                    ),
                ),
            ],
            options={
                "unique_together": {("service_id", "service")},
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notified", models.BooleanField(default=False)),
                (
                    "notified_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when the notification was sent",
                        null=True,
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (0, "Cinema"),
                            (1, "Retail Purchase"),
                            (2, "Rental"),
                            (3, "Online Streaming"),
                        ],
                        db_index=True,
                        default=0,
                        help_text="Send notification when movie is available for ...",
                    ),
                ),
                (
                    "watchlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="movies.watchlist",
                    ),
                ),
            ],
            options={
                "ordering": ("watchlist", "type"),
                "unique_together": {("watchlist", "type")},
            },
        ),
    ]
